language: go

go:
    - 1.2
    - 1.3
    - tip

install: make updatedeps
script:
    - sed -i "s/mitchellh\/packer/henrysher\/packer/g" `find . -name "*.go"`
    - GOMAXPROCS=2 make test
    #- go test -race ./...

matrix:
    allow_failures:
        - go: tip
